name: Zip release excluding docs

on: 
  # Only trigger on push with a version tag
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  Zip-release:
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Make sub-folder for addon files
        run: mkdir image-matcher
      
      - name: Move python files to folder
        run: mv *.py ./image-matcher
        
      - name: Zip addon folder
        run: zip -r image-matcher.zip image-matcher
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: image-matcher.zip
  